In [ ]:
"""
Primero: unir los 6 archivos de weather en uno solo
"""
%pip install numpy
%pip install pandas


import pandas as pd
import numpy as np
from glob import glob

#pd.read_csv('weather01.txt')

Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
weather_files = sorted(glob('weather*.txt'))
weather_files #invoca los nombres de los archivos ordenados con sorted, éste es solo para visualizar el comportamiento

#separar las columnas de cada archivo

# Leer el archivo .txt en un DataFrame
df = pd.read_csv('weather01.txt', header=None)  # 'header=None' ya que no hay encabezado

# Separar los datos en 7 columnas usando el delimitador adecuado
df_separado = df[0].str.split(r'\s+', expand=True)  # Aquí '\s+' representa uno o más espacios

# Asignar los nombres de las columnas
df_separado.columns = ['indice','X', 'year', 'month', 'measure', 'X1', 'X2']

# Guardar el nuevo DataFrame en un archivo de salida
df_separado.to_csv('weather01_separado.txt', index=False, sep='\t')

# Imprimir el DataFrame resultante
print(df_separado)

#eliminar primera columna de cada archivo
# Leer el archivo .txt en un DataFrame
df = pd.read_csv('weather01_separado.txt', delimiter='\t')  # Usa el delimitador adecuado (tabulador o espacio)

# Eliminar la primera columna
df = df.iloc[:, 2:]

# Eliminar la primera fila ya que es solo para los nombres de las columnas
df = df.drop(index=0)

# Guardar el DataFrame sin la primera columna en un nuevo archivo
df.to_csv('newweather01.txt', index=False)

pd.read_csv('newweather01.txt')

    indice    X  year  month            measure    X1    X2
0             X  year  month            measure    X1    X2
1        1    1  2014     12   Max.TemperatureF    64    42
2        2    2  2014     12  Mean.TemperatureF    52    38
3        3    3  2014     12   Min.TemperatureF    39    33
4        4    4  2014     12     Max.Dew.PointF    46    40
..     ...  ...   ...    ...                ...   ...   ...
282    282  282  2015     12  Max.Gust.SpeedMPH    17  <NA>
283    283  283  2015     12    PrecipitationIn  0.14  <NA>
284    284  284  2015     12         CloudCover     7  <NA>
285    285  285  2015     12             Events  Rain  <NA>
286    286  286  2015     12     WindDirDegrees   109  <NA>

[287 rows x 7 columns]

     year  month            measure    X1   X2
0    2014     12   Max.TemperatureF    64   42
1    2014     12  Mean.TemperatureF    52   38
2    2014     12   Min.TemperatureF    39   33
3    2014     12     Max.Dew.PointF    46   40
4    2014     12     MeanDew.PointF    40   27
..    ...    ...                ...   ...  ...
281  2015     12  Max.Gust.SpeedMPH    17  NaN
282  2015     12    PrecipitationIn  0.14  NaN
283  2015     12         CloudCover     7  NaN
284  2015     12             Events  Rain  NaN
285  2015     12     WindDirDegrees   109  NaN

[286 rows x 5 columns]

In [ ]:
#hacer lo mismo con los 6 archivos: 2
df = pd.read_csv('weather02.txt', header=None)
df_separado = df[0].str.split(r'\s+', expand=True)
df_separado.columns = ['indice','X3', 'X4', 'X5', 'X6', 'X7']
df_separado.to_csv('weather02_separado.txt', index=False, sep='\t')
print(df_separado)
df = pd.read_csv('weather02_separado.txt', delimiter='\t')
df = df.iloc[:, 1:]
df = df.drop(index=0)
df.to_csv('newweather02.txt', index=False)
pd.read_csv('newweather02.txt')

#hacer lo mismo con los 6 archivos: 3
df = pd.read_csv('weather03.txt', header=None)
df_separado = df[0].str.split(r'\s+', expand=True)
df_separado.columns = ['indice','X8', 'X9', 'X10', 'X11', 'X12', 'X13','X14']
df_separado.to_csv('weather03_separado.txt', index=False, sep='\t')
print(df_separado)
df = pd.read_csv('weather03_separado.txt', delimiter='\t')
df = df.iloc[:, 1:]
df = df.drop(index=0)
df.to_csv('newweather03.txt', index=False)
pd.read_csv('newweather03.txt')

#hacer lo mismo con los 6 archivos: 4
df = pd.read_csv('weather04.txt', header=None)
df_separado = df[0].str.split(r'\s+', expand=True)
df_separado.columns = ['indice','X15', 'X16', 'X17', 'X18', 'X19', 'X20']
df_separado.to_csv('weather04_separado.txt', index=False, sep='\t')
print(df_separado)
df = pd.read_csv('weather04_separado.txt', delimiter='\t')
df = df.iloc[:, 1:]
df = df.drop(index=0)
df.to_csv('newweather04.txt', index=False)
pd.read_csv('newweather04.txt')                                                  #debería hacer un ciclo con esto? r. después busca

#hacer lo mismo con los 6 archivos: 5
df = pd.read_csv('weather05.txt', header=None)
df_separado = df[0].str.split(r'\s+', expand=True)
df_separado.columns = ['indice','X21', 'X22', 'X23', 'X24', 'X25', 'X26', 'X27']
df_separado.to_csv('weather05_separado.txt', index=False, sep='\t')
print(df_separado)
df = pd.read_csv('weather05_separado.txt', delimiter='\t')
df = df.iloc[:, 1:]
df = df.drop(index=0)
df.to_csv('newweather05.txt', index=False)
pd.read_csv('newweather05.txt')

#hacer lo mismo con los 6 archivos: 6
df = pd.read_csv('weather06.txt', header=None)
df_separado = df[0].str.split(r'\s+', expand=True)
df_separado.columns = ['indice','X28', 'X29', 'X30', 'X31']
df_separado.to_csv('weather06_separado.txt', index=False, sep='\t')
print(df_separado)
df = pd.read_csv('weather06_separado.txt', delimiter='\t')
df = df.iloc[:, 1:]
df = df.drop(index=0)
df.to_csv('newweather06.txt', index=False)
pd.read_csv('newweather06.txt')

    indice    X3    X4    X5    X6    X7
0             X3    X4    X5    X6    X7
1        1    51    43    42    45    38
2        2    44    37    34    42    30
3        3    37    30    26    38    21
4        4    49    24    37    45    36
..     ...   ...   ...   ...   ...   ...
282    282  <NA>  <NA>  <NA>  <NA>  <NA>
283    283  <NA>  <NA>  <NA>  <NA>  <NA>
284    284  <NA>  <NA>  <NA>  <NA>  <NA>
285    285  <NA>  <NA>  <NA>  <NA>  <NA>
286    286  <NA>  <NA>  <NA>  <NA>  <NA>

[287 rows x 6 columns]
    indice    X8    X9   X10   X11   X12   X13   X14
0             X8    X9   X10   X11   X12   X13   X14
1        1    29    49    48    39    39    42    45
2        2    24    39    43    36    35    37    39
3        3    18    29    38    32    31    32    33
4        4    28    49    45    37    28    28    29
..     ...   ...   ...   ...   ...   ...   ...   ...
282    282  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
283    283  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
284    284  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
285    285  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
286    286  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>

[287 rows x 8 columns]
    indice   X15   X16   X17   X18   X19   X20
0            X15   X16   X17   X18   X19   X20
1        1    42    44    49    44    37    36
2        2    37    40    45    40    33    32
3        3    32    35    41    36    29    27
4        4    33    42    46    34    25    30
..     ...   ...   ...   ...   ...   ...   ...
282    282  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
283    283  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
284    284  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
285    285  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
286    286  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>

[287 rows x 7 columns]
    indice   X21   X22   X23   X24   X25   X26   X27
0            X21   X22   X23   X24   X25   X26   X27
1        1    36    44    47    46    59    50    52
2        2    33    39    45    44    52    44    45
3        3    30    33    42    41    44    37    38
4        4    30    39    45    46    58    31    34
..     ...   ...   ...   ...   ...   ...   ...   ...
282    282  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
283    283  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
284    284  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
285    285  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>
286    286  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>

[287 rows x 8 columns]
    indice   X28   X29   X30   X31
0            X28   X29   X30   X31
1        1    52    41    30    30
2        2    46    36    26    25
3        3    40    30    22    20
4        4    42    26    10     8
..     ...   ...   ...   ...   ...
282    282  <NA>  <NA>  <NA>  <NA>
283    283  <NA>  <NA>  <NA>  <NA>
284    284  <NA>  <NA>  <NA>  <NA>
285    285  <NA>  <NA>  <NA>  <NA>
286    286  <NA>  <NA>  <NA>  <NA>

[287 rows x 5 columns]

     X28  X29  X30   X31
0     52   41   30  30.0
1     46   36   26  25.0
2     40   30   22  20.0
3     42   26   10   8.0
4     35   20    4   5.0
..   ...  ...  ...   ...
281  NaN  NaN  NaN   NaN
282  NaN  NaN  NaN   NaN
283  NaN  NaN  NaN   NaN
284  NaN  NaN  NaN   NaN
285  NaN  NaN  NaN   NaN

[286 rows x 4 columns]

In [ ]:
weather_files = sorted(glob('newweather*.txt')) #se ordenan primero
#guardar la concatenación para manipularlo en un solo archivo df
newdf_concatenado = pd.concat((pd.read_csv(file)for file in weather_files), axis='columns').head(286) #la funcion de pandas concatena,en columnas,los archivos en la funcion weather_file después de ordenarla y leerla
nombre_archivo = 'newweather_concatenado.txt'
newdf_concatenado.to_csv(nombre_archivo, index=False)
newdf_concatenado #impresión como variable
pd.read_csv('newweather_concatenado.txt')

,year,month,measure,X1,X2,X3,X4,X5,X6,X7,...,X22,X23,X24,X25,X26,X27,X28,X29,X30,X31
0,2014,12,Max.TemperatureF,64,42,51,43,42,45,38,...,44,47,46,59,50,52.0,52,41,30,30.0
1,2014,12,Mean.TemperatureF,52,38,44,37,34,42,30,...,39,45,44,52,44,45.0,46,36,26,25.0
2,2014,12,Min.TemperatureF,39,33,37,30,26,38,21,...,33,42,41,44,37,38.0,40,30,22,20.0
3,2014,12,Max.Dew.PointF,46,40,49,24,37,45,36,...,39,45,46,58,31,34.0,42,26,10,8.0
4,2014,12,MeanDew.PointF,40,27,42,21,25,40,20,...,34,42,44,43,29,31.0,35,20,4,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,2015,12,Max.Gust.SpeedMPH,17,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,2015,12,PrecipitationIn,0.14,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,2015,12,CloudCover,7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,2015,12,Events,Rain,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,2015,12,WindDirDegrees,109,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
newdf_concatenado.isna().sum() #datos nulos
#newdf_concatenado.isna().sum() / len(newdf_concatenado) #datos nulos en porcentaje, ninguno pasa del 12%

year         0
month        0
measure      0
X1           5
X2          30
X3          25
X4          27
X5          29
X6          32
X7          34
X8          23
X9          24
X10         26
X11         27
X12         33
X13         33
X14         34
X15         23
X16         24
X17         30
X18         33
X19         33
X20         34
X21         23
X22         23
X23         25
X24         27
X25         30
X26         34
X27         34
X28         24
X29         50
X30         53
X31        139
dtype: int64

In [ ]:
#ACOMODAR CON LA FUNCION MELT
#hacer una función que saque la media de cada uno y rellene los datos nulos

In [ ]:
newdf_melt = newdf_concatenado.melt(id_vars=['year','month','measure'])
newdf_melt

      year  month            measure variable value
0     2014     12   Max.TemperatureF       X1    64
1     2014     12  Mean.TemperatureF       X1    52
2     2014     12   Min.TemperatureF       X1    39
3     2014     12     Max.Dew.PointF       X1    46
4     2014     12     MeanDew.PointF       X1    40
...    ...    ...                ...      ...   ...
8861  2015     12  Max.Gust.SpeedMPH      X31   NaN
8862  2015     12    PrecipitationIn      X31   NaN
8863  2015     12         CloudCover      X31   NaN
8864  2015     12             Events      X31   NaN
8865  2015     12     WindDirDegrees      X31   NaN

[8866 rows x 5 columns]

In [ ]:
newdf_melt.dropna(inplace=True) #elimina filas con valores nulos
newdf_melt

      year  month             measure variable  value
0     2014     12    Max.TemperatureF       X1     64
1     2014     12   Mean.TemperatureF       X1     52
2     2014     12    Min.TemperatureF       X1     39
3     2014     12      Max.Dew.PointF       X1     46
4     2014     12      MeanDew.PointF       X1     40
...    ...    ...                 ...      ...    ...
8816  2015     10  Mean.Wind.SpeedMPH      X31    7.0
8817  2015     10   Max.Gust.SpeedMPH      X31   17.0
8818  2015     10     PrecipitationIn      X31    0.0
8819  2015     10          CloudCover      X31    4.0
8821  2015     10      WindDirDegrees      X31  224.0

[7845 rows x 5 columns]

In [ ]:
newdf_melt.rename(columns ={'variable':'day'},inplace=True)
newdf_melt['day'] = newdf_melt['day'].str.extract('(\d+)').astype(int) #cambia el tipo de dato de "day"
newdf_melt['date'] = pd.to_datetime(newdf_melt[['year','month','day']])
newdf_melt

      year  month             measure  day  value       date
0     2014     12    Max.TemperatureF    1     64 2014-12-01
1     2014     12   Mean.TemperatureF    1     52 2014-12-01
2     2014     12    Min.TemperatureF    1     39 2014-12-01
3     2014     12      Max.Dew.PointF    1     46 2014-12-01
4     2014     12      MeanDew.PointF    1     40 2014-12-01
...    ...    ...                 ...  ...    ...        ...
8816  2015     10  Mean.Wind.SpeedMPH   31    7.0 2015-10-31
8817  2015     10   Max.Gust.SpeedMPH   31   17.0 2015-10-31
8818  2015     10     PrecipitationIn   31    0.0 2015-10-31
8819  2015     10          CloudCover   31    4.0 2015-10-31
8821  2015     10      WindDirDegrees   31  224.0 2015-10-31

[7845 rows x 6 columns]

In [ ]:
newdf_melt.drop(['year','month','day'],axis=1,inplace=True) #eliminar las columnas innecesarias
newdf_melt

                 measure  value       date
0       Max.TemperatureF     64 2014-12-01
1      Mean.TemperatureF     52 2014-12-01
2       Min.TemperatureF     39 2014-12-01
3         Max.Dew.PointF     46 2014-12-01
4         MeanDew.PointF     40 2014-12-01
...                  ...    ...        ...
8816  Mean.Wind.SpeedMPH    7.0 2015-10-31
8817   Max.Gust.SpeedMPH   17.0 2015-10-31
8818     PrecipitationIn    0.0 2015-10-31
8819          CloudCover    4.0 2015-10-31
8821      WindDirDegrees  224.0 2015-10-31

[7845 rows x 3 columns]

In [ ]:
df1 = newdf_melt.pivot(index='date',columns='measure',values='value').reset_index()
df1

measure,date,CloudCover,Events,Max.Dew.PointF,Max.Gust.SpeedMPH,Max.Humidity,Max.Sea.Level.PressureIn,Max.TemperatureF,Max.VisibilityMiles,Max.Wind.SpeedMPH,...,Mean.VisibilityMiles,Mean.Wind.SpeedMPH,MeanDew.PointF,Min.DewpointF,Min.Humidity,Min.Sea.Level.PressureIn,Min.TemperatureF,Min.VisibilityMiles,PrecipitationIn,WindDirDegrees
0,2014-12-01,6,Rain,46,29,74,30.45,64,10,22,...,10,13,40,26,52,30.01,39,10,0.01,268
1,2014-12-02,7,Rain-Snow,40,29,92,30.71,42,10,24,...,8,15,27,17,51,30.4,33,2,0.10,62
2,2014-12-03,8,Rain,49,38,100,30.4,51,10,29,...,5,12,42,24,57,29.87,37,1,0.44,254
3,2014-12-04,3,Rain,24,33,69,30.56,43,10,25,...,10,12,21,13,39,30.09,30,10,0.00,292
4,2014-12-05,5,Rain,37,26,85,30.68,42,10,22,...,10,10,25,12,47,30.45,26,5,0.11,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,2015-11-27,7.0,NaN,52.0,32.0,100.0,30.63,64.0,10.0,26.0,...,9.0,14.0,49.0,47.0,56.0,30.15,48.0,5.0,0.0,209.0
362,2015-11-28,8,Rain,50,23,93,30.2,60,10,18,...,9,10,43,36,67,30.11,41,4,0.21,358
363,2015-11-29,4,NaN,33,20,79,30.42,44,10,16,...,10,10,23,15,36,30.19,32,10,0.00,326
364,2015-11-30,6,NaN,26,17,75,30.53,38,10,14,...,10,9,23,18,54,30.39,28,10,0.00,65
365,2015-12-01,7,Rain,43,17,96,30.4,45,10,15,...,8,6,35,25,69,30.01,32,1,0.14,109

In [ ]:
df1.iloc[0:,1:30]

measure,CloudCover,Events,Max.Dew.PointF,Max.Gust.SpeedMPH,Max.Humidity,Max.Sea.Level.PressureIn,Max.TemperatureF,Max.VisibilityMiles,Max.Wind.SpeedMPH,Mean.Humidity,...,Mean.VisibilityMiles,Mean.Wind.SpeedMPH,MeanDew.PointF,Min.DewpointF,Min.Humidity,Min.Sea.Level.PressureIn,Min.TemperatureF,Min.VisibilityMiles,PrecipitationIn,WindDirDegrees
0,6,Rain,46,29,74,30.45,64,10,22,63,...,10,13,40,26,52,30.01,39,10,0.01,268
1,7,Rain-Snow,40,29,92,30.71,42,10,24,72,...,8,15,27,17,51,30.4,33,2,0.10,62
2,8,Rain,49,38,100,30.4,51,10,29,79,...,5,12,42,24,57,29.87,37,1,0.44,254
3,3,Rain,24,33,69,30.56,43,10,25,54,...,10,12,21,13,39,30.09,30,10,0.00,292
4,5,Rain,37,26,85,30.68,42,10,22,66,...,10,10,25,12,47,30.45,26,5,0.11,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,7.0,NaN,52.0,32.0,100.0,30.63,64.0,10.0,26.0,78.0,...,9.0,14.0,49.0,47.0,56.0,30.15,48.0,5.0,0.0,209.0
362,8,Rain,50,23,93,30.2,60,10,18,80,...,9,10,43,36,67,30.11,41,4,0.21,358
363,4,NaN,33,20,79,30.42,44,10,16,58,...,10,10,23,15,36,30.19,32,10,0.00,326
364,6,NaN,26,17,75,30.53,38,10,14,65,...,10,9,23,18,54,30.39,28,10,0.00,65
365,7,Rain,43,17,96,30.4,45,10,15,83,...,8,6,35,25,69,30.01,32,1,0.14,109

In [ ]:
#imprime la cantidad de eventos de cada elemento diferente de la columna "evets"
df1['Events'].value_counts()

Events
Rain                          90
Snow                          31
Rain-Snow                     10
Fog-Rain                       8
Fog-Snow                       7
Fog                            6
Fog-Rain-Snow                  4
Rain-Thunderstorm              4
Fog-Rain-Thunderstorm          3
Thunderstorm                   1
Fog-Rain-Hail-Thunderstorm     1
Name: count, dtype: int64

In [ ]:
df2 = df1.columns.map("-".join)
df2 #permite aplicar una función específica a cada elemento de un objeto iterable

Index(['d-a-t-e', 'C-l-o-u-d-C-o-v-e-r', 'E-v-e-n-t-s',
       'M-a-x-.-D-e-w-.-P-o-i-n-t-F', 'M-a-x-.-G-u-s-t-.-S-p-e-e-d-M-P-H',
       'M-a-x-.-H-u-m-i-d-i-t-y',
       'M-a-x-.-S-e-a-.-L-e-v-e-l-.-P-r-e-s-s-u-r-e-I-n',
       'M-a-x-.-T-e-m-p-e-r-a-t-u-r-e-F',
       'M-a-x-.-V-i-s-i-b-i-l-i-t-y-M-i-l-e-s',
       'M-a-x-.-W-i-n-d-.-S-p-e-e-d-M-P-H', 'M-e-a-n-.-H-u-m-i-d-i-t-y',
       'M-e-a-n-.-S-e-a-.-L-e-v-e-l-.-P-r-e-s-s-u-r-e-I-n',
       'M-e-a-n-.-T-e-m-p-e-r-a-t-u-r-e-F',
       'M-e-a-n-.-V-i-s-i-b-i-l-i-t-y-M-i-l-e-s',
       'M-e-a-n-.-W-i-n-d-.-S-p-e-e-d-M-P-H', 'M-e-a-n-D-e-w-.-P-o-i-n-t-F',
       'M-i-n-.-D-e-w-p-o-i-n-t-F', 'M-i-n-.-H-u-m-i-d-i-t-y',
       'M-i-n-.-S-e-a-.-L-e-v-e-l-.-P-r-e-s-s-u-r-e-I-n',
       'M-i-n-.-T-e-m-p-e-r-a-t-u-r-e-F',
       'M-i-n-.-V-i-s-i-b-i-l-i-t-y-M-i-l-e-s',
       'P-r-e-c-i-p-i-t-a-t-i-o-n-I-n', 'W-i-n-d-D-i-r-D-e-g-r-e-e-s'],
      dtype='object', name='measure')

In [ ]:
# prompt: genera un código como la celda anterior que la función map no separe por letras, debe separar por la palabra completa

import pandas as pd
import numpy as np
from glob import glob

# ... (Your existing code) ...

df2 = df1.columns.map(lambda x: str(x))
df2

Index(['date', 'CloudCover', 'Events', 'Max.Dew.PointF', 'Max.Gust.SpeedMPH',
       'Max.Humidity', 'Max.Sea.Level.PressureIn', 'Max.TemperatureF',
       'Max.VisibilityMiles', 'Max.Wind.SpeedMPH', 'Mean.Humidity',
       'Mean.Sea.Level.PressureIn', 'Mean.TemperatureF',
       'Mean.VisibilityMiles', 'Mean.Wind.SpeedMPH', 'MeanDew.PointF',
       'Min.DewpointF', 'Min.Humidity', 'Min.Sea.Level.PressureIn',
       'Min.TemperatureF', 'Min.VisibilityMiles', 'PrecipitationIn',
       'WindDirDegrees'],
      dtype='object', name='measure')

In [ ]:
df3 = (
    df1.set_axis(df2,axis=1).reset_index()
)
df3

measure,index,d-a-t-e,C-l-o-u-d-C-o-v-e-r,E-v-e-n-t-s,M-a-x-.-D-e-w-.-P-o-i-n-t-F,M-a-x-.-G-u-s-t-.-S-p-e-e-d-M-P-H,M-a-x-.-H-u-m-i-d-i-t-y,M-a-x-.-S-e-a-.-L-e-v-e-l-.-P-r-e-s-s-u-r-e-I-n,M-a-x-.-T-e-m-p-e-r-a-t-u-r-e-F,M-a-x-.-V-i-s-i-b-i-l-i-t-y-M-i-l-e-s,...,M-e-a-n-.-V-i-s-i-b-i-l-i-t-y-M-i-l-e-s,M-e-a-n-.-W-i-n-d-.-S-p-e-e-d-M-P-H,M-e-a-n-D-e-w-.-P-o-i-n-t-F,M-i-n-.-D-e-w-p-o-i-n-t-F,M-i-n-.-H-u-m-i-d-i-t-y,M-i-n-.-S-e-a-.-L-e-v-e-l-.-P-r-e-s-s-u-r-e-I-n,M-i-n-.-T-e-m-p-e-r-a-t-u-r-e-F,M-i-n-.-V-i-s-i-b-i-l-i-t-y-M-i-l-e-s,P-r-e-c-i-p-i-t-a-t-i-o-n-I-n,W-i-n-d-D-i-r-D-e-g-r-e-e-s
0,0,2014-12-01,6,Rain,46,29,74,30.45,64,10,...,10,13,40,26,52,30.01,39,10,0.01,268
1,1,2014-12-02,7,Rain-Snow,40,29,92,30.71,42,10,...,8,15,27,17,51,30.4,33,2,0.10,62
2,2,2014-12-03,8,Rain,49,38,100,30.4,51,10,...,5,12,42,24,57,29.87,37,1,0.44,254
3,3,2014-12-04,3,Rain,24,33,69,30.56,43,10,...,10,12,21,13,39,30.09,30,10,0.00,292
4,4,2014-12-05,5,Rain,37,26,85,30.68,42,10,...,10,10,25,12,47,30.45,26,5,0.11,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,361,2015-11-27,7.0,NaN,52.0,32.0,100.0,30.63,64.0,10.0,...,9.0,14.0,49.0,47.0,56.0,30.15,48.0,5.0,0.0,209.0
362,362,2015-11-28,8,Rain,50,23,93,30.2,60,10,...,9,10,43,36,67,30.11,41,4,0.21,358
363,363,2015-11-29,4,NaN,33,20,79,30.42,44,10,...,10,10,23,15,36,30.19,32,10,0.00,326
364,364,2015-11-30,6,NaN,26,17,75,30.53,38,10,...,10,9,23,18,54,30.39,28,10,0.00,65
365,365,2015-12-01,7,Rain,43,17,96,30.4,45,10,...,8,6,35,25,69,30.01,32,1,0.14,109